In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("D:/DATA/aitpune/college study thingy/dsbdal/prac_exam_questions/7-data_wrangling-laptops/laptop_pricing_dataset_mod1.csv")
df.head()

,Unnamed: 0,Manufacturer,Category,Screen,GPU,OS,CPU_core,Screen_Size_cm,CPU_frequency,RAM_GB,Storage_GB_SSD,Weight_kg,Price
0,0,Acer,4,IPS Panel,2,1,5,35.560,1.6,8,256,1.60,978
1,1,Dell,3,Full HD,1,1,3,39.624,2.0,4,256,2.20,634
2,2,Dell,3,Full HD,1,1,7,39.624,2.7,8,256,2.20,946
3,3,Dell,4,IPS Panel,2,1,5,33.782,1.6,8,128,1.22,1244
4,4,HP,4,Full HD,2,1,7,39.624,1.8,8,256,1.91,837

In [3]:
print(df.isnull().sum())

Unnamed: 0        0
Manufacturer      0
Category          0
Screen            0
GPU               0
OS                0
CPU_core          0
Screen_Size_cm    4
CPU_frequency     0
RAM_GB            0
Storage_GB_SSD    0
Weight_kg         5
Price             0
dtype: int64

In [4]:
df.fillna(df.mean(numeric_only=True), inplace=True)

,Unnamed: 0,Manufacturer,Category,Screen,GPU,OS,CPU_core,Screen_Size_cm,CPU_frequency,RAM_GB,Storage_GB_SSD,Weight_kg,Price
0,0,Acer,4,IPS Panel,2,1,5,35.560,1.6,8,256,1.60,978
1,1,Dell,3,Full HD,1,1,3,39.624,2.0,4,256,2.20,634
2,2,Dell,3,Full HD,1,1,7,39.624,2.7,8,256,2.20,946
3,3,Dell,4,IPS Panel,2,1,5,33.782,1.6,8,128,1.22,1244
4,4,HP,4,Full HD,2,1,7,39.624,1.8,8,256,1.91,837
...,...,...,...,...,...,...,...,...,...,...,...,...,...
233,233,Lenovo,4,IPS Panel,2,1,7,35.560,2.6,8,256,1.70,1891
234,234,Toshiba,3,Full HD,2,1,5,33.782,2.4,8,256,1.20,1950
235,235,Lenovo,4,IPS Panel,2,1,5,30.480,2.6,8,256,1.36,2236
236,236,Lenovo,3,Full HD,3,1,5,39.624,2.5,6,256,2.40,883
237,237,Toshiba,3,Full HD,2,1,5,35.560,2.3,8,256,1.95,1499

In [5]:
df["Weight_kg"] = df["Weight_kg"].astype(str).str.replace("kg", "")
df["Weight_kg"] = pd.to_numeric(df["Weight_kg"], errors='coerce')

df["Screen_Size_cm"] = df["Screen_Size_cm"].astype(str).str.replace("cm", "")
df["Screen_Size_cm"] = pd.to_numeric(df["Screen_Size_cm"], errors='coerce')

In [6]:
df["Screen_Size_inch"] = df["Screen_Size_cm"] / 2.54

In [7]:
df["Weight_pounds"] = df["Weight_kg"] * 2.20462

In [8]:
bins = [0, df["Price"].quantile(0.33), df["Price"].quantile(0.66), df["Price"].max()]
labels = ["Low", "Medium", "High"]

df["Price-binned"] = pd.cut(df["Price"], bins=bins, labels=labels)

In [9]:
df = pd.get_dummies(df, columns=["Screen"], drop_first=True)

In [10]:
df.head()

,Unnamed: 0,Manufacturer,Category,GPU,OS,CPU_core,Screen_Size_cm,CPU_frequency,RAM_GB,Storage_GB_SSD,Weight_kg,Price,Screen_Size_inch,Weight_pounds,Price-binned,Screen_IPS Panel
0,0,Acer,4,2,1,5,35.560,1.6,8,256,1.60,978,14.0,3.527392,Low,True
1,1,Dell,3,1,1,3,39.624,2.0,4,256,2.20,634,15.6,4.850164,Low,False
2,2,Dell,3,1,1,7,39.624,2.7,8,256,2.20,946,15.6,4.850164,Low,False
3,3,Dell,4,2,1,5,33.782,1.6,8,128,1.22,1244,13.3,2.689636,Medium,True
4,4,HP,4,2,1,7,39.624,1.8,8,256,1.91,837,15.6,4.210824,Low,False