In [1]:
import pandas as pd

df = pd.read_csv("D:/DATA/aitpune/college study thingy/dsbdal/prac_exam_questions/24-descriptive-stats/Food_Delivery_Times.csv")

df.head()

,Order_ID,Distance_km,Weather,Traffic_Level,Time_of_Day,Vehicle_Type,Preparation_Time_min,Courier_Experience_yrs,Delivery_Time_min
0,522,7.93,Windy,Low,Afternoon,Scooter,12,1.0,43
1,738,16.42,Clear,Medium,Evening,Bike,20,2.0,84
2,741,9.52,Foggy,Low,Night,Scooter,28,1.0,59
3,661,7.44,Rainy,Medium,Afternoon,Scooter,5,1.0,37
4,412,19.03,Clear,Low,Morning,Bike,16,5.0,68

In [2]:
grouped_stats = df.groupby("Traffic_Level")["Delivery_Time_min"].agg(["mean", "median", "min", "max", "std"])

print("Summary Statistics (Delivery Time grouped by Traffic Level):\n")
print(grouped_stats)

Summary Statistics (Delivery Time grouped by Traffic Level):

                    mean  median  min  max        std
Traffic_Level
High           64.807107    65.0   21  122  21.869356
Low            52.885117    51.0    8  141  21.683646
Medium         56.020513    53.5   13  123  21.186516

In [3]:
value_list = df.groupby("Traffic_Level")["Delivery_Time_min"].apply(list)

print("\nList of Delivery Time values for each Traffic Level:\n")
print(value_list)

List of Delivery Time values for each Traffic Level:

Traffic_Level
High      [53, 33, 37, 56, 108, 45, 82, 69, 60, 40, 62, ...
Low       [43, 59, 68, 57, 49, 35, 73, 76, 35, 50, 24, 2...
Medium    [84, 37, 46, 88, 36, 47, 73, 64, 56, 123, 52, ...
Name: Delivery_Time_min, dtype: object

In [4]:
groups = df.groupby("Traffic_Level")["Delivery_Time_min"]

for name, values in groups:
    print(f"\nTraffic Level: {name}")
    
    print("Mean:", values.mean())
    print("Median:", values.median())
    print("Min:", values.min())
    print("Max:", values.max())
    print("Std:", values.std())
    
    print("Values List:", list(values))

Traffic Level: High
Mean: 64.80710659898477
Median: 65.0
Min: 21
Max: 122
Std: 21.86935583753629
Values List: [53, 33, 37, 56, 108, 45, 82, 69, 60, 40, 62, 42, 74, 72, 69, 73, 94, 87, 70, 52, 69, 79, 80, 105, 91, 116, 75, 36, 41, 85, 75, 31, 54, 46, 54, 108, 100, 92, 85, 21, 66, 67, 58, 67, 96, 51, 30, 60, 72, 108, 85, 66, 50, 67, 96, 112, 57, 65, 63, 28, 72, 93, 67, 36, 59, 60, 70, 55, 66, 32, 67, 55, 88, 92, 41, 70, 38, 93, 63, 47, 112, 102, 37, 46, 70, 88, 28, 37, 71, 61, 41, 77, 70, 44, 35, 74, 92, 43, 42, 21, 80, 34, 59, 44, 60, 80, 65, 48, 43, 58, 71, 106, 63, 78, 47, 53, 58, 76, 54, 27, 48, 83, 57, 59, 65, 77, 29, 48, 55, 97, 56, 53, 70, 96, 75, 44, 68, 72, 33, 46, 63, 51, 95, 88, 86, 71, 73, 59, 67, 80, 104, 39, 39, 95, 55, 40, 55, 30, 101, 40, 71, 57, 38, 74, 39, 61, 65, 72, 90, 56, 73, 95, 100, 24, 53, 48, 75, 85, 44, 48, 68, 42, 50, 106, 122, 60, 64, 38, 71, 59, 98, 91, 81, 38, 70, 54, 81]

Traffic Level: Low
Mean: 52.885117493472585
Median: 51.0
Min: 8
Max: 141
Std: 21.683645559210472
Values List: [43, 59, 68, 57, 49, 35, 73, 76, 35, 50, 24, 27, 72, 58, 70, 70, 8, 36, 43, 36, 36, 56, 47, 50, 31, 35, 44, 23, 69, 38, 52, 68, 22, 111, 51, 41, 69, 49, 32, 65, 68, 28, 44, 70, 48, 49, 14, 30, 35, 69, 37, 57, 74, 41, 26, 141, 29, 59, 30, 92, 16, 37, 49, 60, 17, 33, 32, 61, 64, 69, 32, 60, 48, 80, 36, 43, 50, 42, 62, 30, 69, 30, 21, 82, 55, 35, 72, 71, 32, 38, 87, 48, 37, 51, 55, 48, 68, 71, 59, 78, 48, 42, 46, 67, 37, 85, 21, 51, 70, 14, 66, 25, 42, 22, 62, 51, 47, 40, 17, 43, 63, 72, 28, 71, 101, 63, 57, 42, 28, 26, 52, 48, 39, 59, 66, 77, 52, 20, 71, 21, 29, 16, 49, 76, 61, 36, 63, 42, 69, 61, 69, 28, 43, 28, 89, 50, 36, 85, 58, 49, 53, 85, 67, 34, 33, 48, 57, 34, 94, 31, 56, 63, 60, 52, 52, 31, 35, 141, 41, 31, 22, 66, 74, 91, 46, 54, 49, 66, 83, 62, 69, 60, 86, 51, 41, 42, 29, 37, 56, 68, 30, 79, 34, 75, 15, 17, 32, 40, 86, 43, 52, 23, 71, 64, 100, 50, 34, 57, 61, 70, 60, 21, 41, 48, 64, 57, 109, 58, 41, 72, 32, 97, 71, 42, 68, 45, 47, 48, 56, 58, 23, 26, 71, 71, 18, 91, 99, 51, 42, 48, 32, 54, 31, 57, 90, 26, 83, 78, 77, 37, 39, 65, 56, 94, 31, 72, 56, 69, 43, 51, 61, 46, 31, 74, 20, 36, 73, 34, 56, 36, 42, 61, 28, 61, 45, 66, 21, 66, 42, 63, 14, 49, 37, 53, 38, 75, 92, 48, 84, 68, 70, 25, 33, 69, 33, 45, 78, 126, 27, 17, 26, 68, 68, 87, 66, 70, 61, 83, 18, 84, 77, 30, 55, 65, 37, 27, 63, 28, 78, 54, 84, 56, 77, 50, 31, 83, 66, 46, 53, 35, 43, 77, 62, 60, 42, 42, 44, 74, 36, 77, 51, 25, 27, 97, 30, 75, 60, 79, 114, 45, 34, 101, 24, 63, 28, 30, 71, 50, 27, 53, 62, 39, 56, 39, 72, 62, 29, 53, 35, 79, 71, 55, 58]

Traffic Level: Medium
Mean: 56.02051282051282
Median: 53.5
Min: 13
Max: 123
Std: 21.186516295607714
Values List: [84, 37, 46, 88, 36, 47, 73, 64, 56, 123, 52, 111, 44, 73, 45, 61, 34, 47, 52, 67, 32, 67, 56, 104, 61, 31, 54, 87, 48, 46, 92, 71, 43, 42, 45, 76, 28, 80, 57, 31, 65, 44, 73, 91, 65, 77, 58, 56, 44, 78, 62, 82, 25, 28, 49, 113, 43, 60, 54, 66, 37, 68, 68, 30, 46, 47, 65, 44, 24, 47, 43, 47, 35, 44, 58, 65, 17, 16, 72, 51, 89, 60, 57, 36, 41, 27, 49, 62, 64, 73, 87, 30, 52, 22, 75, 13, 32, 35, 47, 58, 66, 23, 52, 32, 90, 55, 76, 47, 77, 65, 26, 58, 17, 44, 33, 55, 67, 52, 100, 71, 30, 39, 73, 46, 66, 53, 27, 32, 54, 14, 75, 27, 83, 70, 47, 109, 43, 28, 48, 59, 19, 62, 80, 71, 38, 71, 39, 35, 71, 44, 89, 67, 48, 41, 49, 50, 46, 78, 77, 79, 80, 103, 89, 49, 80, 35, 23, 57, 52, 30, 68, 84, 28, 85, 108, 73, 52, 44, 34, 62, 47, 47, 60, 53, 57, 25, 68, 34, 62, 115, 67, 65, 80, 48, 68, 73, 40, 33, 85, 42, 49, 75, 57, 36, 30, 45, 51, 46, 63, 74, 87, 116, 98, 37, 36, 43, 43, 24, 65, 59, 86, 66, 56, 90, 35, 19, 38, 49, 38, 77, 64, 39, 47, 71, 52, 60, 49, 71, 75, 105, 77, 41, 51, 38, 59, 89, 39, 22, 101, 27, 34, 34, 79, 44, 58, 48, 51, 44, 81, 72, 40, 43, 49, 42, 76, 72, 70, 65, 56, 70, 57, 44, 63, 35, 49, 44, 46, 77, 43, 47, 48, 74, 78, 89, 51, 64, 73, 69, 38, 72, 91, 54, 16, 69, 38, 94, 45, 67, 62, 55, 105, 61, 35, 23, 43, 89, 60, 51, 91, 44, 58, 90, 64, 51, 49, 65, 88, 47, 55, 17, 66, 67, 29, 33, 44, 42, 49, 39, 45, 22, 74, 65, 51, 27, 39, 56, 60, 77, 94, 50, 57, 47, 77, 64, 29, 54, 51, 76, 27, 54, 98, 37, 46, 73, 24, 28, 25, 93, 62, 34, 44, 79, 42, 41, 79, 53, 71, 41, 43, 43, 17, 65, 70, 65, 32, 85, 29, 59, 64, 35, 78, 79, 38, 28, 58, 24, 50, 92, 58, 25]

In [5]:
import seaborn as sns

iris = sns.load_dataset("iris")

iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [6]:
iris["species"].unique()

<StringArray>
['setosa', 'versicolor', 'virginica']
Length: 3, dtype: str

In [7]:
species_list = iris["species"].unique()

In [8]:
for sp in species_list:
    
    print(f"\nStatistics for {sp}:\n")
    
    subset = iris[iris["species"] == sp]
    
    print("Mean:\n", subset.mean(numeric_only=True))
    
    print("\nStandard Deviation:\n", subset.std(numeric_only=True))
    
    print("\nPercentiles:\n", subset.quantile([0.25, 0.5, 0.75], numeric_only=True))

Statistics for setosa:

Mean:
 sepal_length    5.006
sepal_width     3.428
petal_length    1.462
petal_width     0.246
dtype: float64

Standard Deviation:
 sepal_length    0.352490
sepal_width     0.379064
petal_length    0.173664
petal_width     0.105386
dtype: float64

Percentiles:
       sepal_length  sepal_width  petal_length  petal_width
0.25           4.8        3.200         1.400          0.2
0.50           5.0        3.400         1.500          0.2
0.75           5.2        3.675         1.575          0.3

Statistics for versicolor:

Mean:
 sepal_length    5.936
sepal_width     2.770
petal_length    4.260
petal_width     1.326
dtype: float64

Standard Deviation:
 sepal_length    0.516171
sepal_width     0.313798
petal_length    0.469911
petal_width     0.197753
dtype: float64

Percentiles:
       sepal_length  sepal_width  petal_length  petal_width
0.25           5.6        2.525          4.00          1.2
0.50           5.9        2.800          4.35          1.3
0.75           6.3        3.000          4.60          1.5

Statistics for virginica:

Mean:
 sepal_length    6.588
sepal_width     2.974
petal_length    5.552
petal_width     2.026
dtype: float64

Standard Deviation:
 sepal_length    0.635880
sepal_width     0.322497
petal_length    0.551895
petal_width     0.274650
dtype: float64

Percentiles:
       sepal_length  sepal_width  petal_length  petal_width
0.25         6.225        2.800         5.100          1.8
0.50         6.500        3.000         5.550          2.0
0.75         6.900        3.175         5.875          2.3